const DEFAULT_ACCEPTED_TYPES = ['string', 'integer', 'float', 'timestamp', 'boolean', 'object', 'map', 'list', 'otr']
const DEFAULT_ENTRIES = ['_name', '_otr']
const DEFAULT_REQUIRED_VALUE = false;
const DEFAULT_MIN_LENGTH = 0;
const DEFAULT_NOT_EMPTY_VALUE = false;


module.exports = {
    DEFAULT_ACCEPTED_TYPES: DEFAULT_ACCEPTED_TYPES,
    DEFAULT_ENTRIES: DEFAULT_ENTRIES,
    DEFAULT_REQUIRED_VALUE: DEFAULT_REQUIRED_VALUE,
    DEFAULT_MIN_LENGTH: DEFAULT_MIN_LENGTH,
    DEFAULT_NOT_EMPTY_VALUE: DEFAULT_NOT_EMPTY_VALUE,
}